import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/auth');
  await page.getByRole('button', { name: 'Registrarse' }).click();
  await page.getByRole('textbox', { name: 'Elige un usuario' }).click();
  await page.getByRole('textbox', { name: 'Elige un usuario' }).fill('test');
  await page.getByRole('textbox', { name: 'Introduce tu email' }).click();
  await page.getByRole('textbox', { name: 'Introduce tu email' }).fill('prueba@test.com');
  await page.getByRole('textbox', { name: 'Crea una contraseña segura' }).click();
  await page.getByRole('textbox', { name: 'Crea una contraseña segura' }).fill('Prueba123');
  await page.getByRole('button', { name: 'Crear cuenta' }).click();
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByRole('textbox', { name: 'Introduce tu usuario' }).click();
  await page.getByRole('textbox', { name: 'Introduce tu usuario' }).fill('test');
  await page.getByRole('textbox', { name: 'Introduce tu contraseña' }).click();
  await page.getByRole('textbox', { name: 'Introduce tu contraseña' }).fill('Prueba123');
  await page.getByRole('button', { name: 'Entrar' }).click();
  await page.getByRole('button', { name: 'add_circle Crear análisis' }).click();
  await page.getByRole('button', { name: 'add_circle Nuevo análisis' }).click();
  await page.getByRole('textbox', { name: 'Nombre del análisis' }).click();
  await page.getByRole('textbox', { name: 'Nombre del análisis' }).fill('prueba');
  await page.getByRole('textbox', { name: 'Descripción' }).click();
  await page.getByRole('textbox', { name: 'Descripción' }).fill('test');
  const datasetInput = page.locator('input[type="file"][accept=".csv,text/csv"]').first();
  await expect(datasetInput).toBeAttached();
  await datasetInput.setInputFiles('tests/e2e/fixtures/test_file.csv');
  await page.getByRole('button', { name: 'bar_chart Gráficas SAES' }).click();
  await page.getByRole('button', { name: 'play_arrow Crear y ejecutar' }).click();
  await page.getByRole('link', { name: 'insights Ver gráficas' }).click();
  await page.getByRole('textbox', { name: 'Buscar gráfica' }).click();
  await page.getByRole('textbox', { name: 'Buscar gráfica' }).fill('convergen');
  await page.getByRole('button', { name: 'Configuración de cuadrícula' }).click();
  await page.getByRole('button', { name: 'Visible' }).click();
  await page.getByRole('button', { name: 'Grande' }).click();
  await page.getByRole('button', { name: 'analysis.plots.columnCount' }).nth(2).click();
  await page.getByRole('button', { name: 'Filtros' }).click();
  await page.getByRole('button', { name: 'PNG' }).click();
  await page.getByRole('button', { name: 'Opciones de evolución' }).click();
  await page.getByRole('button', { name: 'Ver evoluciones generadas' }).click();
  await page.getByRole('button', { name: 'check Aplicar' }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'folder_zip Descargar todo' }).click();
  const download = await downloadPromise;
  await page.getByRole('link', { name: 'arrow_back Volver' }).click();
  await page.getByRole('button', { name: 'play_arrow Crear Reportes SAES' }).click();
  await page.getByRole('link', { name: 'table_chart Ver reportes' }).click();
  await page.getByRole('button', { name: 'Activar comparación' }).click();
  await page.getByRole('button', { name: 'Desactivar comparación' }).click();
  const download2Promise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'folder_zip Descargar todo' }).click();
  const download2 = await download2Promise;
  await page.getByRole('link', { name: 'arrow_back Volver' }).click();
  const downloadPromise3 = page.waitForEvent('download');
  await page.getByRole('button', { name: 'download Descargar' }).click();
  const download3 = await downloadPromise3;
  await page.getByRole('button', { name: 'play_arrow Crear Notebook SAES' }).click();
  const download4Promise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'download Descargar' }).nth(2).click();
  const download4 = await download4Promise;
  await page.getByRole('link', { name: 'arrow_back Volver' }).click();
  await page.getByRole('button', { name: 'filter_alt Filtros expand_more' }).click();
  await page.getByRole('combobox').first().selectOption('completed');
  await page.getByRole('combobox').first().selectOption('created');
  await page.getByRole('combobox').first().selectOption('all');
  await page.getByRole('button', { name: 'filter_alt Filtros expand_less' }).click();
  await page.getByRole('button', { name: 'filter_alt Filtros expand_more' }).click();
  await page.getByRole('combobox').nth(1).selectOption('date_asc');
  await page.getByRole('button', { name: 'filter_alt Filtros expand_less' }).click();
  await page.getByRole('button', { name: 'Cambiar a modo oscuro' }).click();
  await page.getByRole('button', { name: 'Menú de perfil' }).click();
  await page.getByRole('button', { name: 'settings Configuración' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('test3');
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('prueba10@test.com');
  await page.getByRole('button', { name: 'Guardar perfil' }).click();
  await page.getByRole('textbox').nth(2).fill('Prueba123');
  await page.getByRole('textbox').nth(3).fill('Prueba1234');
  await page.getByRole('button', { name: 'Cambiar contraseña' }).click();
  await page.getByRole('button', { name: 'Eliminar cuenta' }).click();
  await page.getByRole('button', { name: 'Cancelar' }).click();
  await page.getByRole('button', { name: '🇪🇸 Español expand_more' }).click();
  await page.getByRole('button', { name: '🇬🇧 English' }).click();
  await page.getByRole('button', { name: 'Delete account' }).click();
  await page.getByRole('button', { name: 'Yes, delete account' }).click();
});